name: disaster_management
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  animated_bottom_navigation_bar: ^1.0.1
  auto_size_text: ^3.0.0
  country_state_city_picker: ^1.2.8
  csc_picker: ^0.2.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^1.1.1+1
  flutter_zoom_drawer: ^2.1.2
  get: ^4.6.5
  google_fonts: ^3.0.1
  syncfusion_flutter_charts: ^19.1.54

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
